### ISSUE TITLE
Error when importing service

### ISSUE THREAD

**Issue by lit26** [bamada/nest-slack-bolt#134]
<img width="1003" alt="Screen Shot 2023-04-10 at 11 56 31 PM" src="https://user-images.githubusercontent.com/51225681/231083962-a5dea887-eded-4a07-9dd5-2e48aba024f0.png">

**Comment by ngajhede** [comment]
Hi @lit26 

Not sure if you are still facing this issue. I ran into this myself. The correct path is `import { SlackService } from 'nestjs-slack-bolt/dist/services/slack.service';`

Hope this helps.

**Comment by lit26** [comment]
Yup, that helps. The readme needs to be updated.
