### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by ngajhede** [bamada/nest-slack-bolt#148]
Bonjour @bamada ! 😄 

I was wondering if this is still under development? We are using this package at my work, and we recently updated to NestJS 10.0.5. It causes issues because this package hasn't been updated. Would you be able to update the packages etc? Will you accept PR's?

I am simply just asking because other people have raised issues here that is unanswered. 
If not, I would be glad to help maintaining and develop this package further. 😄 

Nicolaj

**Comment by lit26** [comment]
Same.

**Comment by bamada** [comment]
Hello 
glad to know you are using it I will now dedicate time to maintaining it properly.
I'm  going to update it with Nestjs 10.X

**Comment by ngajhede** [comment]
> Hello glad to know you are using it I will now dedicate time to maintaining it properly. I'm going to update it with Nestjs 10.X

Yay! Great to hear!

**Comment by tinhochu** [comment]
Let us know if you need help
