### ISSUE TITLE
Does this support installation stores?

### ISSUE THREAD

**Issue by n6rayan** [bamada/nest-slack-bolt#179]
The `@slack/bolt` package supports the ability to store, fetch and delete installations, see here: https://slack.dev/bolt-js/concepts#authenticating-oauth

I figured this could be achieved by doing something like:
```js
import { Module } from '@nestjs/common';
import { SlackModule } from 'nestjs-slack-bolt';

@Module({
  imports: [
    SlackModule.forRoot({
      signingSecret: process.env.SLACK_SIGNING_SECRET,
      token: process.env.SLACK_BOT_TOKEN,
      installationStore: {
        fetchInstallation: async (installQuery) => { ... },
        storeInstallation: async (installation) => { ... },
        deleteInstallation: async (installQuery) => { ... }
      },
    }),
  ],
})
export class YourModule {}
```
Please let me know if something of the sort is supported, or if there is plans to support it.

**Comment by bamada** [comment]
@n6rayan  this is not yet possible. 
I adding it to my todo list

**Comment by bamada** [comment]
Here is the PR https://github.com/bamada/nest-slack-bolt/pull/186
