### ISSUE TITLE
What is the default endpoint for a Slash command? 

### ISSUE THREAD

**Issue by kkasaei** [bamada/nest-slack-bolt#218]
Should a command goes to `https://domain.com/command` or  `https://domain.com/slack/command` or `https://domain.com/slack/event/command`

Seems like Bolt uses `/slack/events` as the default route. however good to have an example setup of the route needed to call a slash command.
Thanks

https://slack.dev/bolt-js/tutorial/getting-started-http#:~:text=%F0%9F%92%A1%20By%20default%2C%20Bolt%20uses,set%20up%20to%20handle%20interactivity!

💡 By default, Bolt uses the same endpoint for interactive components that it uses for events, so use the same request URL as above (in the example, it was https://8e8ec2d7.ngrok.io/slack/events). Press the Save Changes button in the lower right hand corner, and that’s it. Your app is set up to handle interactivity!

**Comment by bamada** [comment]
Hi, 
here is an example of how to use the slash method.

```typescript
  @Command('/list')
  async list({ ack, respond, command }: SlackCommandMiddlewareArgs) {
    await ack();
    await respond(`${command.text}`);
  }
```

I didn't understand your question about the URL but here is the doc I used to build my example https://slack.dev/bolt-js/concepts#commands.

If you still have an issue could you give me more details?
