### ISSUE TITLE
How to apply the Event Subscription URL.

### ISSUE THREAD

**Issue by inkweon7269** [bamada/nest-slack-bolt#342]
To apply Event Subscriptions, you need to implement slack/events, but I need example code on how to set this up in the package.

```typescript
import { App, Receiver, ReceiverEvent } from '@slack/bolt';
import { Injectable } from '@nestjs/common';
import { Request, Response } from 'express';

@Injectable()
export class AppReceiver implements Receiver {
  private boltApp: App;

  public init(boltApp: App): void {
    this.boltApp = boltApp; // Slack Bolt 앱 인스턴스 저장
  }

  public async start(): Promise<void> {}

  public async stop(): Promise<void> {}

  public async handleRequest(req: Request, res: Response): Promise<void> {
    const { body } = req;

    const event: ReceiverEvent = {
      body,
      ack: async (response) => {
        if (response) {
          res.status(200).json(response);
        } else {
          res.status(200).send();
        }
      },
    };

    try {
      await this.boltApp.processEvent(event);
    } catch (error) {
      console.error('Error processing Slack event:', error);
      res.status(500).send('Internal Server Error');
    }
  }
}

```

```typescript
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { SlackModule } from 'nestjs-slack-bolt';
import { AppReceiver } from './app.receiver';

@Module({
  imports: [
    SlackModule.forRoot({
      token: 'xxxxx',
      appToken: 'xxxxx',
      clientId: 'xxxxxx',
      clientSecret: 'xxxxxx',
      signingSecret: 'xxxxxx',
      socketMode: false,
      receiver: new AppReceiver(),
    }),
  ],
  controllers: [AppController],
  providers: [AppService, AppReceiver],
})
export class AppModule {}
```

```typescript
import { Controller, Post, Req, Res } from '@nestjs/common';
import { AppService } from './app.service';
import { AppReceiver } from './app.receiver';
import { Request, Response } from 'express';

@Controller('slack')
export class AppController {
  constructor(
    private readonly appService: AppService,
    private readonly appReceiver: AppReceiver,
  ) {}

  @Post('events')
  async handleEvents(@Req() req: Request, @Res() res: Response): Promise<void> {
    await this.appReceiver.handleRequest(req, res);
  }
}
````
<img width="1014" alt="스크린샷 2024-05-12 오후 2 40 31" src="https://github.com/bamada/nest-slack-bolt/assets/9918075/43efd2bc-272f-4692-ae78-b9274f36bdaf">

<img width="722" alt="스크린샷 2024-05-12 오후 2 51 33" src="https://github.com/bamada/nest-slack-bolt/assets/9918075/ddbfc484-c212-4bd9-a8b0-82f2ca76c054">

Or how can the ExpressReceiver be used in this module to apply it to the Slack Events API?

**Comment by bamada** [comment]
<img width="400" alt="Screenshot 2024-05-17 at 00 03 00" src="https://github.com/bamada/nest-slack-bolt/assets/7466570/c4a7f64c-cf04-4484-b838-4df30229ba1c">

In your implementation, you don't take into account the `challenge` part that is not managed by this module.
doc: https://api.slack.com/events/url_verification

Moreover, you can also use [@Event](https://github.com/bamada/nest-slack-bolt?tab=readme-ov-file#handling-an-event) annotation to subscribe to a specific event without the `challenge`. In this case, you need to add the events you want to subscribe to your SlackApp.
<img width="400" alt="Screenshot 2024-05-16 at 23 57 48" src="https://github.com/bamada/nest-slack-bolt/assets/7466570/6cda962a-8e12-4683-ba2f-43b2ad2d6be3">
